security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users:
            entity:
                class: App\Entity\User
                property: username
        users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            stateless: false
            access_denied_handler: App\Security\AccessDeniedHandler
            lazy: true
            provider: users
            custom_authenticator: App\Security\LoginFormAuthenticator
            entry_point: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                target: /
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 86400        # 1 day (in seconds)
                path: /
                name: REMEMBERME        # cookie name (optional)
                always_remember_me: false

            two_factor:
                auth_form_path: /2fa
                check_path: /2fa_check
                default_target_path: /admin
                always_use_default_target_path: true

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
         - { path: ^/admin, roles: [ROLE_Administrator, ROLE_Medic, ROLE_Psiholog, ROLE_Asistent, ROLE_Receptioner, ROLE_Test] }
         - { path: ^/consultatii, roles: [ROLE_Administrator, ROLE_Medic, ROLE_Psiholog, ROLE_Asistent, ROLE_Receptioner, ROLE_Test] }
         - { path: ^/pacienti, roles: [ROLE_Administrator, ROLE_Medic, ROLE_Psiholog, ROLE_Asistent, ROLE_Receptioner, ROLE_Test] }
         - { path: ^/owners, roles: [ROLE_Administrator, ROLE_Test] }
         - { path: ^/rapoarte, roles: [ROLE_Administrator, ROLE_Medic, ROLE_Psiholog, ROLE_Asistent, ROLE_Receptioner, ROLE_Test] }
         - { path: ^/servicii_preturi, roles: [ROLE_Administrator, ROLE_Medic, ROLE_Psiholog, ROLE_Asistent, ROLE_Receptioner, ROLE_Test] }
         - { path: ^/consultatii_curente_cabinet, roles: [ROLE_Administrator, ROLE_Medic, ROLE_Psiholog, ROLE_Asistent, ROLE_Receptioner, ROLE_Test] }
         - { path: ^/clienti_pj, roles: [ROLE_Administrator, ROLE_Receptioner, ROLE_Test] }
         - { path: ^/facturi, roles: [ROLE_Administrator, ROLE_Receptioner, ROLE_Medic, ROLE_Test] }
         - { path: ^/consultatii_nefacturate, roles: [ROLE_Administrator, ROLE_Receptioner, ROLE_Medic, ROLE_Test] }
