version: '3.9'

services:
  app:
    image: cet_app
    build:
      context: .
    container_name: cet_app
    ports:
      - "8089:80"
    volumes:
      - ./cet_test:/var/www/html/cet_test
    depends_on:
      - db
    environment:
      APP_ENV: test
      DATABASE_URL: "mysql://symfony:symfony@db:3306/cet_test?serverVersion=8.0"
    working_dir: /var/www/html/cet_test

  db:
    image: mysql:8.0
    container_name: cet_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cet_test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
